version: '3.8'

networks:
  zivelogin-network-prod:
    external: true

services:
  hrumble-new-frontend:
    build:
      context: ./Hrumbles-Front-End_UI
      dockerfile: Dockerfile
    container_name: hrumble-new-frontend
    restart: unless-stopped
    networks:
      - zivelogin-network-prod
    ports:
      - "5003:80"
    volumes:
      - ./frontend/dist:/dist
    environment:
      VITE_SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticGV5ZmlldHJ3bGh3Y3dxaGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDA5NjEsImV4cCI6MjA1NDQxNjk2MX0.A-K4DO6D2qQZ66qIXY4BlmoHxc-W5B0itV-HAAM84YA"
      VITE_SUPABASE_URL: "https://kbpeyfietrwlhwcwqhjw.supabase.co"

        # --- NEW SERVICE FOR THE MARKETING WEBSITE ---
  hrumble-website:
    build:
      context: ./hrumbles-website
      dockerfile: Dockerfile
    container_name: hrumble-website
    restart: unless-stopped
    networks:
      - zivelogin-network-prod
    ports:
      - "5004:80" # Assign a new host port (5004) for the website
